image: microsoft/dotnet:latest

stages:
    - build_image
    - push_image
    - image_test
    - deploy

before_script:
        - "docker login -u $GITLAB_USER -p $GITLAB_PASSWORD gitlab.domainname.az:4567"

build_docker: 
    stage: build_image
    script: 
        - "docker build -t gitlab.domainname.az:4567/sariyevrustam/dotnetcore-bakcend-project:$CI_PIPELINE_IID ."
    only:
        - master

push_image:
    stage: push_image
    script:
        - "docker push gitlab.domainname.az:4567/sariyevrustam/dotnetcore-bakcend-project:$CI_PIPELINE_IID"
    only:
        - master

images_test:
    stage: image_test
    script: 
       - echo "Image Tested"


deploying to production:
    stage: deploy
    script:  
        - "docker stop dotnetcore-bakcend-project || true && docker rm dotnetcore-bakcend-project || true"
        - "docker run -d -p 81:80 --mount source=resource,target=/app/volume-resources --name dotnetcore-bakcend-project gitlab.domainname.az:4567/sariyevrustam/dotnetcore-bakcend-project:$CI_PIPELINE_IID"
    environment:
        name: production
    only:
        - master


