version: "3.3"

services:

  reverseproxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
      - "8443:443"
    restart: always

  backendresource:
    depends_on:
      - reverseproxy
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
